// <auto-generated />
namespace HW_TPL.DataAccess.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class InitTwo : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(InitTwo));
        
        string IMigrationMetadata.Id
        {
            get { return "201906111147174_InitTwo"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
